version: '3.1'

services:
    database_dev:
        container_name: parking-control-dev
        image: postgres
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=parking-control-dev
        ports:
            - "5432:5432"
        volumes:
            - ./database-local:/docker-entrypoint-initdb.d